[package]
name = "dht11-driver-rust"
version = "0.1.0"
authors = ["Gabriel Zuser <zusergabriel@gmail.com>"]
edition = "2021"
description = "A platform-agnostic no-std driver for the DHT11 sensor using typestates for safety."
license = "MIT"
repository = "https://github.com/Wkesther2/dht11-driver-rust.git"
readme = "README.md"
keywords = ["dht11", "sensor", "embedded-hal", "stm32", "no-std"]
categories = ["embedded", "hardware-support", "no-std"]

[lib]
harness = false

[[example]]
name = "stm32f407_dwt"
path = "examples/stm32f407_dwt.rs"
required-features = ["use-dwt"] 

[[example]]
name = "stm32f407_no_dwt"
path = "examples/stm32f407_no_dwt.rs"

# --- Dependencies ---

[dependencies]
defmt = { version = "0.3", optional = true }
embedded-hal = "1.0.0"
fugit = "0.3.9"

# Optional Cortex-M support for DWT
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"], optional = true }

[dev-dependencies]
stm32f4xx-hal = { version = "0.23.0", features = ["stm32f407"] } 
cortex-m-rt = "0.7"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
panic-halt = "1.0.0"

# --- Features ---

[features]
default = ["use-defmt"]
use-dwt = ["dep:cortex-m"]
use-defmt = ["dep:defmt"]

# --- Profiles ---

[profile.dev]
opt-level = "s"
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = 'fat'
codegen-units = 1
debug = 2
